global:
  smtp_from: 'tochange@gmail.com'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: 'tochange@gmail.com'
  smtp_auth_password: 'tochange'
templates:
- '/etc/alertmanager/template/*.tmpl'
route:
 group_by: ['alertname']
 group_wait: 3s
 group_interval: 5s
 repeat_interval: 1h
 receiver: mail-receiver
receivers:
- name: mail-receiver
  email_configs:
  - to: 'tochange@gmail.com'
    send_resolved: true